name: gaussian_splatting
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  - nvidia/label/cuda-11.8.0
dependencies:
  - cuda-toolkit
  - einops
  - imageio
  - open3d
  - pytorch-cuda=11.8
  - plyfile
  - python=3.10
  - pip=22.3.1
  - pytorch==2.2.2
  - torchaudio==2.2.2
  - torchvision==0.17.2
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
