name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia/label/cuda-11.6.0
dependencies:
  - pytorch-cuda=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - cuda-toolkit
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
